In [131]:
import random
import numpy as np
from scipy.sparse import coo_matrix

In [134]:
def generate_random_matrix_params(m_min, m_max):
    rows = random.randint(m_min, m_max)
    cols = random.randint(m_min, m_max)
    min_val, max_val = sorted([random.randint(m_min, m_max) for _ in range(2)])
    return rows, cols, min_val, max_val

def generate_sparse_matrix(rows, columns, min_value, max_value, density=0.2):
    num_non_zero_values = int(rows * columns * density)
    data = np.random.randint(min_value, max_value + 1, size=num_non_zero_values)
    row_indices = np.random.randint(0, rows, size=num_non_zero_values)
    col_indices = np.random.randint(0, columns, size=num_non_zero_values)
    sparse_matrix = coo_matrix((data, (row_indices, col_indices)), shape=(rows, columns))
    return sparse_matrix

def print_matrix_details(matrix, name):
    print(f"Size of matrix {name}: {matrix.shape[0]}x{matrix.shape[1]}")
    print(matrix)
    print()
    
def multiply_matrices(matrix_a, matrix_b):
    try:
        return np.dot(matrix_a, matrix_b)
    except ValueError as e:
        raise ValueError("Matrix dimensions are not aligned for multiplication.") from e
        
def demonstrate_matrix_multiplication(cycles=3):
    for i in range(cycles):
        matrix_params_A = generate_random_matrix_params(0, 10)
        matrix_A = generate_sparse_matrix(*matrix_params_A).toarray()
        print_matrix_details(matrix_A, "A")
        
        matrix_params_B = generate_random_matrix_params(0, 10)
        matrix_params_B = (matrix_A.shape[1], matrix_params_B[1], *matrix_params_B[2:])
        matrix_B = generate_sparse_matrix(*matrix_params_B).toarray()
        print_matrix_details(matrix_B, "B")
        
        try:
            result = multiply_matrices(matrix_A, matrix_B)
            print("The result of the matrix multiplication between matrix A and matrix B is:")
            print(result)
        except Exception as e:
            print(e)
        
        print(f"END OF CYCLE {i + 1}")
        print()

In [135]:
demonstrate_matrix_multiplication()

Size of matrix A: 8x2
[[0 0]
 [2 7]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 6]]

Size of matrix B: 2x6
[[0 0 1 0 0 0]
 [0 3 0 0 0 0]]

The result of the matrix multiplication between matrix A and matrix B is:
[[ 0  0  0  0  0  0]
 [ 0 21  2  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0 18  0  0  0  0]]
END OF CYCLE 1

Size of matrix A: 5x1
[[0]
 [0]
 [6]
 [0]
 [0]]

Size of matrix B: 1x5
[[0 0 0 1 0]]

The result of the matrix multiplication between matrix A and matrix B is:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 6 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
END OF CYCLE 2

Size of matrix A: 4x2
[[0 0]
 [0 0]
 [9 0]
 [0 0]]

Size of matrix B: 2x4
[[0 8 0 0]
 [0 0 0 0]]

The result of the matrix multiplication between matrix A and matrix B is:
[[ 0  0  0  0]
 [ 0  0  0  0]
 [ 0 72  0  0]
 [ 0  0  0  0]]
END OF CYCLE 3

